#Bashtop theme with nord palette (https://www.nordtheme.com)
#by Justin Zobel <justin.zobel@gmail.com>

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
#theme[main_bg]="#282A36"
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#ffdddd"

# Title color for boxes
theme[title]="#f8f8f2"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#ffffff"

# Background color of selected item in processes box
theme[selected_bg]="#44475A"

# Foreground color of selected item in processes box
theme[selected_fg]="#ECEFF4"

# Color of inactive/disabled text
theme[inactive_fg]="#6272a4"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ff0000"

# Cpu box outline color
theme[cpu_box]="#ff0000"

# Memory/disks box outline color
theme[mem_box]="#ff0000"

# Net up/down box outline color
theme[net_box]="#ff0000"

# Processes box outline color
theme[proc_box]="#ff0000"

# Box divider line and small boxes line color
theme[div_line]="#ff0000"

# Temperature graph colors
theme[temp_start]="#ff0000"
theme[temp_mid]="#ff0000"
theme[temp_end]="#ff0000"

# CPU graph colors
theme[cpu_start]="#ff0000"
theme[cpu_mid]="#ff0000"
theme[cpu_end]="#ff0000"

# Mem/Disk free meter
theme[free_start]="#ff0000"
theme[free_mid]="#ff0000"
theme[free_end]="#ff0000"

# Mem/Disk cached meter
theme[cached_start]="#ff0000"
theme[cached_mid]="#ff0000"
theme[cached_end]="#ff0000"

# Mem/Disk available meter
theme[available_start]="#ff0000"
theme[available_mid]="#ff0000"
theme[available_end]="#ff0000"

# Mem/Disk used meter
theme[used_start]="#ff0000"
theme[used_mid]="#ff0000"
theme[used_end]="#ff0000"

# Download graph colors
theme[download_start]="#ff0000"
theme[download_mid]="#ff0000"
theme[download_end]="#ff0000"

# Upload graph colors
theme[upload_start]="#ff0000"
theme[upload_mid]="#ff0000"
theme[upload_end]="#ff0000"
